name: Release

on:
  push:
    branches: [main]

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    uses: kad-products/platform/.github/workflows/release.yaml@better-shared-workflows
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets: inherit
